apiVersion: v1
kind: PersistentVolume
metadata:
  name: rayne-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data
    type: DirectoryOrCreate
