apiVersion: v1
kind: Pod
metadata:
  name: rayne
spec:
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: rayne-pvc

  initContainers:
    - name: volume-permissions
      image: busybox
      command: ["sh", "-c", "mkdir -p /data && chown 1000:1000 /data"]
      securityContext:
        runAsUser: 0 # root in the init container
      volumeMounts:
        - name: data
          mountPath: /data

  containers:
    - name: rayne
      image: archlinux:latest
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      volumeMounts:
        - name: data
          mountPath: /data
      command: ["/bin/bash"]
      args: ["-c", "while true; do sleep 30; done;"]
